language: python
python: "2.7"

# commands to install packages
before_install:
  - sudo apt-get install node-less
  - sudo apt-get install coffeescript

# command to install dependencies
install:
  - pip install -r tests/requirements.txt
  - pip install freezes
