# Site settings
title: "Your awesome web title"
email: your@email.com
description: Here is your awesome website description
url: "http://www.your-awesome.com"
twitter: your-twitter-name
github:  your-github-name
disqus_shortname: your-disqus-name
ga_account: your-ga-account